server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
        enabled: true
      routes:
        - id: payment_routh  #路由id，没有固定规则，但是要求唯一
#          uri: http://localhost:8001  #匹配后提供的地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get/**    #断言，路径相匹配的进行路由

        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/**
#            - After=2021-05-31T10:58:40.560+08:00[Asia/Shanghai]
#            - Cookie=username,zzyy
#            - Header=X-Request-Id,\d+ #请求头要有X-Request-Id属性并且值为正数的正则表达式
#            - Host=**.baidu.com
#          filters:
#            - AddRequestHeader=Test,gateway

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka
